//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupun
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Email { get; set; }
        public string Total { get; set; }
        public string Rate { get; set; }
        public string ExpireDate { get; set; }
    }
}
