//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Integration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReservationsEntities : DbContext
    {
        public ReservationsEntities()
            : base("name=ReservationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agency> Agency { get; set; }
        public DbSet<Agents> Agents { get; set; }
        public DbSet<ExtraService> ExtraService { get; set; }
        public DbSet<Rhotel> Rhotel { get; set; }
        public DbSet<RHRoom> RHRoom { get; set; }
        public DbSet<Tour> Tour { get; set; }
        public DbSet<Transfers> Transfers { get; set; }
        public DbSet<Members> Members { get; set; }
        public DbSet<Coupun> Coupun { get; set; }
        public DbSet<DeadLine> DeadLine { get; set; }
        public DbSet<Marketman> Marketman { get; set; }
        public DbSet<ChangeRoom> ChangeRoom { get; set; }
        public DbSet<hotelchange> hotelchange { get; set; }
        public DbSet<ininvoice> ininvoice { get; set; }
        public DbSet<Reservations> Reservations { get; set; }
        public DbSet<Payments> Payments { get; set; }
        public DbSet<uyeler> uyeler { get; set; }
        public DbSet<old> old { get; set; }
        public DbSet<tahsilat> tahsilat { get; set; }
    }
}
