//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tahsilat
    {
        public int id { get; set; }
        public string kulladi { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<double> toplam { get; set; }
        public string staff { get; set; }
        public string odeme_tipi { get; set; }
        public string orderid { get; set; }
        public string odeme_detay { get; set; }
        public Nullable<System.DateTime> odeme_tarihi { get; set; }
        public string ilgilidosya { get; set; }
    }
}
