//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LocaleStringResource> LocaleStringResources { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<VisitorTypes> VisitorTypes { get; set; }
        public virtual DbSet<Picture> PictureSet { get; set; }
        public virtual DbSet<SystemLog> SystemLog { get; set; }
        public virtual DbSet<Agency> Agency { get; set; }
        public virtual DbSet<ExtraService> ExtraService { get; set; }
        public virtual DbSet<Rhotel> Rhotel { get; set; }
        public virtual DbSet<RHRoom> RHRoom { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<Transfers> Transfers { get; set; }
        public virtual DbSet<DeadLine> DeadLine { get; set; }
        public virtual DbSet<Marketman> Marketman { get; set; }
        public virtual DbSet<ChangeRoom> ChangeRoom { get; set; }
        public virtual DbSet<hotelchange> hotelchange { get; set; }
        public virtual DbSet<ininvoice> ininvoice { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierServices> SupplierServicesSet { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<SupplierPayment> SupplierPaymentSet { get; set; }
        public virtual DbSet<DataTour> DataTours { get; set; }
        public virtual DbSet<DataPackage> DataPackages { get; set; }
        public virtual DbSet<DataHotel> DataHotels { get; set; }
        public virtual DbSet<OfflineRooms> OfflineRooms { get; set; }
        public virtual DbSet<OnlineRooms> OnlineRooms { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Unpaid> unpaids { get; set; }
        public virtual DbSet<Filelog> Filelogs { get; set; }
        public virtual DbSet<HotelsReport> HotelsReports { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<AdvancePayments> AdvancePayments { get; set; }
        public virtual DbSet<LoginLog> LoginLog { get; set; }
    }
}
