//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filelog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filelog()
        {
            this.Action = "\"\"";
            this.shortMessage = "\"\"";
        }
    
        public int Id { get; set; }
        public int ref_file { get; set; }
        public int ref_member { get; set; }
        public string Action { get; set; }
        public string shortMessage { get; set; }
    
        public virtual Members Visitor { get; set; }
        public virtual Reservations Reservations { get; set; }
    }
}
