//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelsReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelsReport()
        {
            this.Year = 0;
            this.Jan = 0m;
            this.Feb = 0m;
            this.Mar = 0m;
            this.Apr = 0m;
            this.May = 0m;
            this.Jun = 0m;
            this.Jul = 0m;
            this.Aug = 0m;
            this.Sep = 0m;
            this.Oct = 0m;
            this.Nov = 0m;
            this.Dec = 0m;
            this.Total = 0m;
            this.Costs = 0m;
        }
    
        public int Id { get; set; }
        public int ref_agency { get; set; }
        public string City { get; set; }
        public int Year { get; set; }
        public decimal Jan { get; set; }
        public decimal Feb { get; set; }
        public decimal Mar { get; set; }
        public decimal Apr { get; set; }
        public decimal May { get; set; }
        public decimal Jun { get; set; }
        public decimal Jul { get; set; }
        public decimal Aug { get; set; }
        public decimal Sep { get; set; }
        public decimal Oct { get; set; }
        public decimal Nov { get; set; }
        public decimal Dec { get; set; }
        public decimal Total { get; set; }
        public decimal Costs { get; set; }
        public int ref_hotel { get; set; }
    
        public virtual DataHotel DataHotel { get; set; }
    }
}
