//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.IPaddress = "";
            this.SenderEmail = "";
            this.FirstName = "";
            this.LastName = "";
            this.languageId = 0;
            this.Deleted = false;
            this.Country = "";
            this.City = "";
            this.State = "";
            this.VisitorTypes = new HashSet<VisitorTypes>();
            this.MReservations = new HashSet<Reservations>();
        }
    
        public int Id { get; set; }
        public string IPaddress { get; set; }
        public System.DateTime lastActivityFromUtc { get; set; }
        public string SenderEmail { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int languageId { get; set; }
        public System.DateTime Created_utc { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> VisitorGuid { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string RecoveryToken { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
        public bool active { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public bool manager { get; set; }
        public bool accountManager { get; set; }
        public bool reservationManager { get; set; }
        public string tel { get; set; }
        public string emailPassword { get; set; }
        public bool reservations { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorTypes> VisitorTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservations> MReservations { get; set; }
    }
}
