//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineRooms
    {
        public int Id { get; set; }
        public Nullable<int> hid { get; set; }
        public string roomtype { get; set; }
        public string board { get; set; }
        public string market { get; set; }
        public Nullable<System.DateTime> validfrom { get; set; }
        public Nullable<System.DateTime> validuntil { get; set; }
        public string room_ficilites { get; set; }
        public Nullable<int> maxpax { get; set; }
        public Nullable<decimal> bedprice { get; set; }
        public Nullable<decimal> bedbreakfastprice { get; set; }
        public Nullable<decimal> extrabed { get; set; }
        public string note { get; set; }
        public string name { get; set; }
    
        public virtual DataHotel Hotel { get; set; }
    }
}
