//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.Year = 0;
            this.Jan = 0m;
            this.Feb = 0m;
            this.Mar = 0m;
            this.Apr = 0m;
            this.May = 0m;
            this.Jun = 0m;
            this.Jul = 0m;
            this.Aug = 0m;
            this.Sep = 0m;
            this.Oct = 0m;
            this.Nov = 0m;
            this.Dec = 0m;
            this.Total = 0m;
            this.Costs = 0m;
            this.JanCost = 0m;
            this.FebCost = 0m;
            this.MarCost = 0m;
            this.AprCost = 0m;
            this.MayCost = 0m;
            this.JunCost = 0m;
            this.JulCost = 0m;
            this.AugCost = 0m;
            this.SepCost = 0m;
            this.OctCost = 0m;
            this.NovCost = 0m;
            this.DecCost = 0m;
        }
    
        public int Id { get; set; }
        public int ref_agency { get; set; }
        public string Country { get; set; }
        public int Year { get; set; }
        public decimal Jan { get; set; }
        public decimal Feb { get; set; }
        public decimal Mar { get; set; }
        public decimal Apr { get; set; }
        public decimal May { get; set; }
        public decimal Jun { get; set; }
        public decimal Jul { get; set; }
        public decimal Aug { get; set; }
        public decimal Sep { get; set; }
        public decimal Oct { get; set; }
        public decimal Nov { get; set; }
        public decimal Dec { get; set; }
        public decimal Total { get; set; }
        public decimal Costs { get; set; }
        public decimal JanCost { get; set; }
        public decimal FebCost { get; set; }
        public decimal MarCost { get; set; }
        public decimal AprCost { get; set; }
        public decimal MayCost { get; set; }
        public decimal JunCost { get; set; }
        public decimal JulCost { get; set; }
        public decimal AugCost { get; set; }
        public decimal SepCost { get; set; }
        public decimal OctCost { get; set; }
        public decimal NovCost { get; set; }
        public decimal DecCost { get; set; }
    
        public virtual Agency Agency { get; set; }
    }
}
