//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierServices
    {
        public int Id { get; set; }
        public int ref_supplierkey { get; set; }
        public string Servie { get; set; }
        public string descreption { get; set; }
        public decimal buy { get; set; }
        public decimal sell { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
