//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public Agency()
        {
            this.Agents = new HashSet<Agents>();
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int ID { get; set; }
        public string AgencyName { get; set; }
        public bool Active { get; set; }
        public string Market { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Adress { get; set; }
        public decimal Commision { get; set; }
        public string Credit { get; set; }
        public string CreditAmount { get; set; }
        public string note { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string joindate { get; set; }
    
        public virtual ICollection<Agents> Agents { get; set; }
        public virtual ICollection<Reservations> Reservations { get; set; }
    }
}
