//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        public int ID { get; set; }
        public int AID { get; set; }
        public bool active { get; set; }
        public System.DateTime date { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string skype { get; set; }
        public string other { get; set; }
    
        public virtual Agency Agency { get; set; }
    }
}
