//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public Members()
        {
            this.Reservations1 = new HashSet<Reservations>();
        }
    
        public int ID { get; set; }
        public bool active { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public bool manager { get; set; }
        public bool accountManager { get; set; }
        public bool reservationManager { get; set; }
        public bool doreservations { get; set; }
        public string tel { get; set; }
        public string emailPassword { get; set; }
        public bool reservations { get; set; }
    
        public virtual ICollection<Reservations> Reservations1 { get; set; }
    }
}
