//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class old
    {
        public int res_id { get; set; }
        public string market { get; set; }
        public string Hoteladi { get; set; }
        public string Hotelkod { get; set; }
        public Nullable<int> emailsay { get; set; }
        public Nullable<int> belgesay { get; set; }
        public string email { get; set; }
        public string aciklama { get; set; }
        public string dosyano { get; set; }
        public string Rezervlist { get; set; }
        public string Rezervkod { get; set; }
        public Nullable<System.Guid> Rezervkodmu { get; set; }
        public string Checkindate { get; set; }
        public string Checkoutdate { get; set; }
        public string Totalnights { get; set; }
        public string Board { get; set; }
        public string OdaTipi { get; set; }
        public string Sngfiyat { get; set; }
        public string Sngoda { get; set; }
        public string Sngmaliyet { get; set; }
        public string Sngtotal { get; set; }
        public string Doublefiyat { get; set; }
        public string Doubleoda { get; set; }
        public string Doublemaliyet { get; set; }
        public string Doubletotal { get; set; }
        public string Exbedfiyat { get; set; }
        public string Exbedadet { get; set; }
        public string Exbedtotal { get; set; }
        public string Chdfreeadet { get; set; }
        public string Chd50fiyat { get; set; }
        public string Chd50adet { get; set; }
        public string Chd50total { get; set; }
        public string Rezervtotal { get; set; }
        public string hotelmaliyet { get; set; }
        public Nullable<double> hoteltotal { get; set; }
        public string maliyettotal { get; set; }
        public string Grandtotal { get; set; }
        public string Komisyontotal { get; set; }
        public string netpayment { get; set; }
        public string Info { get; set; }
        public string Turadi { get; set; }
        public string Turpaxcins { get; set; }
        public string Turprice { get; set; }
        public string Turadet { get; set; }
        public Nullable<double> Turtotal { get; set; }
        public string Turmaliyet { get; set; }
        public Nullable<double> fullturtotal { get; set; }
        public string Turtarih { get; set; }
        public string TurRegion { get; set; }
        public string Transferadi { get; set; }
        public string Transferpaxcins { get; set; }
        public string Transferadet { get; set; }
        public string Transferprice { get; set; }
        public string Transfermaliyet { get; set; }
        public Nullable<int> Transfertotal { get; set; }
        public Nullable<int> fulltransfertotal { get; set; }
        public string Transfertarih { get; set; }
        public string TransferRegion { get; set; }
        public string Transferflightno { get; set; }
        public string Transferflighttime { get; set; }
        public string komisyon { get; set; }
        public string kulladi { get; set; }
        public bool reconfirm { get; set; }
        public bool confirm { get; set; }
        public bool cancel { get; set; }
        public bool onay { get; set; }
        public bool degisiklik { get; set; }
        public bool payment { get; set; }
        public bool otel { get; set; }
        public string otel_bilgi { get; set; }
        public string notlar { get; set; }
        public string otel_tarih { get; set; }
        public string yedek { get; set; }
        public string rezervdurum { get; set; }
        public Nullable<int> yedeksayi { get; set; }
        public bool partlyconfirm { get; set; }
        public bool tamamdir { get; set; }
        public string odeme { get; set; }
        public bool belge { get; set; }
        public bool iptal_belge { get; set; }
        public bool degisiklik_belge { get; set; }
        public string birim { get; set; }
        public string mudahale { get; set; }
        public Nullable<System.DateTime> mudahale_tarih { get; set; }
        public string bizimkiler { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.DateTime> ilktarih { get; set; }
        public Nullable<int> Rezervkodu { get; set; }
        public Nullable<System.DateTime> iptal_tarih { get; set; }
        public Nullable<int> degisiklikfark { get; set; }
        public Nullable<int> kasa { get; set; }
        public bool kasahareketi { get; set; }
        public bool silinecek { get; set; }
        public bool online { get; set; }
        public bool onlineiptal { get; set; }
        public string provider { get; set; }
        public string onlineFilename { get; set; }
        public Nullable<System.DateTime> onlineiptaltarih { get; set; }
        public string cancelationtext { get; set; }
        public string Triplefiyat { get; set; }
        public string Tripleadet { get; set; }
        public string Tripletotal { get; set; }
        public string SENDMAIL { get; set; }
        public bool SENDPDF { get; set; }
        public string PDFFILE { get; set; }
    }
}
