//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int ID { get; set; }
        public int RID { get; set; }
        public System.DateTime date { get; set; }
        public string type { get; set; }
        public decimal Payment { get; set; }
        public string note { get; set; }
        public string Member { get; set; }
        public string Currency { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Reservations Reservations { get; set; }
    }
}
