//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int ID { get; set; }
        public int RID { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public decimal Cost { get; set; }
        public decimal Total { get; set; }
        public string customer { get; set; }
        public string note { get; set; }
        public int Pax { get; set; }
        public string pickuptime { get; set; }
        public string pickup { get; set; }
        public string dropoff { get; set; }
        public string city { get; set; }
        public string car { get; set; }
        public string guide { get; set; }
    
        public virtual Reservations Reservations { get; set; }
    }
}
