//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeler
    {
        public int ID { get; set; }
        public string kulladi { get; set; }
        public string sifre { get; set; }
        public bool onay { get; set; }
        public string market { get; set; }
        public string ulke { get; set; }
        public string email { get; set; }
        public string indirim { get; set; }
        public string kredi { get; set; }
        public string komisyon { get; set; }
        public string adi { get; set; }
        public string agent_type { get; set; }
        public string soyadi { get; set; }
        public string acente_code { get; set; }
        public string firma { get; set; }
        public string fax { get; set; }
        public string tel { get; set; }
        public string sehir { get; set; }
        public Nullable<System.DateTime> uyelik_tarihi { get; set; }
        public Nullable<System.DateTime> son_giris_tarihi { get; set; }
        public Nullable<double> giris_sayisi { get; set; }
        public string uye_ip { get; set; }
        public string cevap { get; set; }
        public string sifresoru { get; set; }
        public string adres { get; set; }
        public string IP { get; set; }
        public bool gecici_kredi { get; set; }
        public string cperson { get; set; }
        public string remarks { get; set; }
        public string czipcode { get; set; }
        public string iata { get; set; }
        public string iperson { get; set; }
        public string iemail { get; set; }
        public string iadres { get; set; }
        public string isehir { get; set; }
        public string izipcode { get; set; }
        public string iulke { get; set; }
        public string itel { get; set; }
        public string ifax { get; set; }
        public string logo { get; set; }
        public string ceptel { get; set; }
        public string iceptel { get; set; }
        public bool subagent { get; set; }
    }
}
