//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agency()
        {
            this.Reservations = new HashSet<Reservations>();
            this.Report = new HashSet<Report>();
            this.Unpaid = new HashSet<Unpaid>();
            this.AdvancePayment = new HashSet<AdvancePayments>();
        }
    
        public int ID { get; set; }
        public string AgencyName { get; set; }
        public bool Active { get; set; }
        public string Market { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Adress { get; set; }
        public decimal Commision { get; set; }
        public string Credit { get; set; }
        public string CreditAmount { get; set; }
        public string note { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string joindate { get; set; }
        public string username { get; set; }
        public string contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservations> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unpaid> Unpaid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvancePayments> AdvancePayment { get; set; }
    }
}
