//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataHotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataHotel()
        {
            this.OfflineRooms = new HashSet<OfflineRooms>();
            this.OnlineRooms = new HashSet<OnlineRooms>();
            this.HotelsReport = new HashSet<HotelsReport>();
            this.Rhotel = new HashSet<Rhotel>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string zip { get; set; }
        public string adress { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<decimal> minrate { get; set; }
        public Nullable<decimal> maxrate { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> rooms { get; set; }
        public string map_longitude { get; set; }
        public string map_latitude { get; set; }
        public string url_booking { get; set; }
        public string photo { get; set; }
        public string desc { get; set; }
        public string desc_ar { get; set; }
        public Nullable<int> bookingID { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string rname { get; set; }
        public bool deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfflineRooms> OfflineRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineRooms> OnlineRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelsReport> HotelsReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rhotel> Rhotel { get; set; }
    }
}
