//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservations()
        {
            this.ExtraService = new HashSet<ExtraService>();
            this.Rhotel = new HashSet<Rhotel>();
            this.Tour = new HashSet<Tour>();
            this.Transfers = new HashSet<Transfers>();
            this.ininvoice = new HashSet<ininvoice>();
            this.Payments = new HashSet<Payments>();
            this.Flight = new HashSet<Flight>();
            this.Filelog = new HashSet<Filelog>();
            this.Unpaid = new HashSet<Unpaid>();
            this.hotelchange = new HashSet<hotelchange>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string ref_marketman { get; set; }
        public int ref_member { get; set; }
        public Nullable<int> ref_agency { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> net { get; set; }
        public Nullable<decimal> commision { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> discountid { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> profit { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> priceTL { get; set; }
        public Nullable<decimal> costTL { get; set; }
        public string curency { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public System.DateTime balanceDate { get; set; }
        public System.DateTime updatedate { get; set; }
        public string updateuser { get; set; }
        public bool reconfirmed { get; set; }
        public string vocher { get; set; }
        public bool sendmail { get; set; }
        public string note { get; set; }
        public string agencystaff { get; set; }
        public decimal balance { get; set; }
        public System.DateTime checkindate { get; set; }
        public bool IsB2B { get; set; }
        public int Ref_CustomerId { get; set; }
        public string HCN { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraService> ExtraService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rhotel> Rhotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfers> Transfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ininvoice> ininvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
        public virtual Members Visitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filelog> Filelog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unpaid> Unpaid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hotelchange> hotelchange { get; set; }
    }
}
