//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rhotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rhotel()
        {
            this.RHRoom = new HashSet<RHRoom>();
        }
    
        public int ID { get; set; }
        public int RID { get; set; }
        public string name { get; set; }
        public Nullable<int> hid { get; set; }
        public System.DateTime checkout { get; set; }
        public System.DateTime checkin { get; set; }
        public decimal Cost { get; set; }
        public decimal Total { get; set; }
        public string customer { get; set; }
        public string note { get; set; }
        public bool Confirmed { get; set; }
        public bool SendHotel { get; set; }
        public int ref_supplier { get; set; }
        public decimal buyCom { get; set; }
        public decimal sellCom { get; set; }
        public bool IsBuyRate { get; set; }
        public bool IsSellRate { get; set; }
        public string SupplierCode { get; set; }
        public bool IsCash { get; set; }
        public Nullable<System.DateTime> CashDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RHRoom> RHRoom { get; set; }
        public virtual Reservations Reservations { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual DataHotel DataHotel { get; set; }
    }
}
