//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfers
    {
        public int ID { get; set; }
        public int RID { get; set; }
        public System.DateTime date { get; set; }
        public decimal Cost { get; set; }
        public decimal Total { get; set; }
        public string customer { get; set; }
        public string note { get; set; }
        public int pax { get; set; }
        public string city { get; set; }
        public string pickup { get; set; }
        public string dropoff { get; set; }
        public string flightCode { get; set; }
        public string flightTime { get; set; }
        public string car { get; set; }
        public string guide { get; set; }
        public bool lockbuying { get; set; }
        public bool lockSelling { get; set; }
        public int ref_supplier { get; set; }
        public decimal buyCom { get; set; }
        public decimal sellCom { get; set; }
        public bool IsBuyRate { get; set; }
        public bool IsSellRate { get; set; }
        public string SupplierCode { get; set; }
    
        public virtual Reservations Reservations { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
