//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unpaid
    {
        public int Id { get; set; }
        public int ref_file { get; set; }
        public decimal amount { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime CheckoutDate { get; set; }
        public bool Paid { get; set; }
        public string PaymentDate { get; set; }
        public int ref_agency { get; set; }
    
        public virtual Reservations Reservations { get; set; }
        public virtual Agency Agency { get; set; }
    }
}
